version: '3'
services:
  db:
    image: mysql:5.6
    environment:
    - MYSQL_ROOT_PASSWORD=dalongdemo
    - MYSQL_DATABASE=juicefs
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    ports:
    - "3306:3306"
  s3:
    image: minio/minio
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio123"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"